# Generated by Django 3.0.4 on 2020-05-29 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'content')},
        ),
        migrations.RemoveField(
            model_name='post',
            name='message_html',
        ),
    ]
