# Generated by Django 3.0.8 on 2021-01-20 14:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_post_publish'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'content', 'title')},
        ),
    ]
